config/routes.rb
Rails.application.routes.draw do
  get '/users/show', to: 'users#show'
  devise_for :users
  get '/meals/today', to: 'meals#today'
  get '/meals/week', to: 'meals#week'
  resources :meals
  root to: "meals#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
   validates :name, :calories, :protein, :carbs, :fat,  :presence => true
   belongs_to :user

   scope :this_weeks_meals, -> { where("DATE(created_at) > ?", (Date.today).to_time - 7.days) }
   scope :todays_meals, -> { where("DATE(created_at) > ?", (Date.today).to_time - 1.days) }

   def self.total_calories
     calories = 0
     Meal.all.each do |meal|
       calories+= meal.calories
     end
     calories
   end

   def self.total_protein
     protein = 0
     Meal.all.each do |meal|
       protein+= meal.protein
     end
     protein
   end

   def self.total_carbs
     carbs = 0
     Meal.all.each do |meal|
       carbs+= meal.carbs
     end
     carbs
   end

   def self.total_fat
     fat = 0
     Meal.all.each do |meal|
       fat+= meal.fat
     end
     fat
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.where(user_id: current_user.id)
  end

  def today
    @meals = Meal.where(user_id: current_user.id).todays_meals
    render :index
  end

  def week
    @meals = Meal.where(user_id: current_user.id).this_weeks_meals
    render :index
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)
    current_user.meals << @meal

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:name, :calories, :protein, :carbs, :fat, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealTracker</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <nav class="navbar sticky-top navbar-expand-sm navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="/users/show"> Your Account </a>
          <a class="nav-item nav-link" href="/meals/today"> Today's Meals </a>
          <a class="nav-item nav-link" href="/meals/week"> This Week's Meals </a>
          <a class="nav-item nav-link" href="/meals"> All Meals </a>
          <a class="nav-item nav-link" href="/meals/new"> Create Meal </a>
          <p class="nav-item nav-link"><%= link_to("Sign Out", destroy_user_session_path, :method => 'delete', class: "btn btn-primary", role: "button") %><p>
        </div>
      </div>
    </nav>

      <% else %>
      <nav class="navbar sticky-top navbar-expand-sm navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <p class="nav-item nav-link"><%= link_to("Sign Up", new_user_registration_path, class: "btn btn-primary", role: "button") %></p>
            <p class="nav-item nav-link"><%= link_to('Login', new_user_session_path, class: "btn btn-primary", role: "button")  %></p>
          </div>
        </div>
      </nav>
    <%end %>
    <br>
    <div class="container">
    <%= content_tag(:div, flash[:error], :id => "flash_error", class: "alert alert-danger alert-dismissable", data: { dismiss: 'alert' }) if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice", class: "alert alert-success alert-dismissable", data: { dismiss: 'alert' }) if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert", class: "alert alert-danger alert-dismissable", data: { dismiss: 'alert' }) if flash[:alert] %>
    <%= yield %>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_with(model: meal, local: true) do |form| %>
  <% if meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name, id: :meal_name, class: "form-control", placeholder: "Name" %>
  </div>

  <div class="form-group">
    <%= form.number_field :calories, id: :meal_calories, class: "form-control", placeholder: "Calories" %>
  </div>

  <div class="form-group">
    <%= form.number_field :protein, id: :meal_protein, class: "form-control", placeholder: "Protein" %>
  </div>

  <div class="form-group">
    <%= form.number_field :carbs, id: :meal_carbs, class: "form-control", placeholder: "Carbs" %>
  </div>

  <div class="form-group">
    <%= form.number_field :fat, id: :meal_fat, class: "form-control", placeholder: "Fat" %>
  </div>

  <div class="form-group">
    <%= form.text_field :description, id: :meal_description, class: "form-control", placeholder: "Description" %>
  </div>

  <div class="actions">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
  <br>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'View', @meal, class: "btn btn-primary", role: "button" %>
<%= link_to 'Back', meals_path, class: "btn btn-primary", role: "button" %>

app/views/meals/index.html.erb
<h1>Meals</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Calories</th>
      <th>Protein</th>
      <th>Carbs</th>
      <th>Fat</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.name %></td>
        <td><%= meal.calories %></td>
        <td><%= meal.protein %></td>
        <td><%= meal.carbs %></td>
        <td><%= meal.fat %></td>
        <td><%= meal.description %></td>
        <td><%= link_to 'View', meal, class: "btn btn-primary", role: "button" %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal), class: "btn btn-primary", role: "button" %></td>
        <td><%= link_to 'Delete', meal, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary", role: "button" %></td>
      </tr>
    <% end %>
      <tr>
        <td>Totals</td>
        <td><%= @meals.total_calories %></td>
        <td><%= @meals.total_protein %></td>
        <td><%= @meals.total_carbs %></td>
        <td><%= @meals.total_fat %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
  </tbody>
</table>

<br>

app/views/meals/new.html.erb
<h1>New Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Back', meals_path, class: "btn btn-primary", role: "button" %>

app/views/meals/show.html.erb
<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Name:</strong>
  <%= @meal.name %>
</p>


<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Calories:</strong>
  <%= @meal.calories %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Protein:</strong>
  <%= @meal.protein %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Carbs:</strong>
  <%= @meal.carbs %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Fat:</strong>
  <%= @meal.fat %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Description:</strong>
  <%= @meal.description %>
</p>

<%= link_to 'Edit', edit_meal_path(@meal), class: "btn btn-primary", role: "button" %>
<%= link_to 'Back', meals_path, class: "btn btn-primary", role: "button" %>

app/views/users/show.html.erb
<h3>Signed in as: <%= @user.email %></h3>
<h5>Total Meals Created: <%= @user.meals.count %></h5>